
# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - echo Installing dependencies...
      - npm install
      - npm install -g @angular/cli
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.0.0.1744-linux.zip
      - unzip sonar-scanner-cli-4.0.0.1744-linux.zip
      - export PATH=$PATH:./sonar-scanner-cli-4.0.0.1744-linux/bin/
  pre_build:
    commands:
      - echo Testing the app
      - npm run test:ci
      - sonar-scanner -Dsonar.projectKey=SergioV85_quest-stat-viewer -Dsonar.organization=sergiov85-github -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=799270451643b073ac2ee494720d741d6f79293f
  build:
    commands:
      - echo Build the app
      - npm run build
  post_build:
    commands:
      - echo Build completed
# Include only the files required for your application to run.
# Do not use recursively include artifacts from node_modules directory as it will include unnecessary packages
# used only for building and testing.
# ExpressJS apps will need other artifact directories included (bin/*, public/*, routes/*, views/* etc).
artifacts:
  files:
    - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
