
# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
      java: openjdk8
    commands:
      - echo Installing node.js dependencies
      - npm install
      - echo Installing SonarQube Scanner
      - npm install -g sonarqube-scanner
  build:
    commands:
      - echo Testing the app
      - npm run test:ci
      - echo Test completed
  post_build:
    commands:
      - echo Run the Sonar Scanner
      - sonar-scanner -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=SergioV85_quest-stat-viewer -Dsonar.organization=sergiov85-github -Dsonar.login=799270451643b073ac2ee494720d741d6f79293f -Dsonar.sources=src -Dsonar.tests=src -Dsonar.test.inclusions="**/*.spec.ts" -Dsonar.exclusions="dist/**, e2e/**, node_modules/**, coverage/**, karma.conf.js, src/*.ts, src/environments/**, src/**/*.mock.*, src/**/*.config.ts, *.js" -Dsonar.typescript.tsconfigPath=tsconfig.json -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info -Dsonar.sourceEncoding=UTF-8
      - echo Scan completed
