import { mergeRight } from 'ramda';
import { GameDetailsState } from '@app-common/models';
import { mockedGameDetails } from '@app-common/mocks/games.mock';

import { GAME_DETAILS_ACTIONS } from '@app-core/game-details/actions/game-details.actions';
import { gameDetailsReducer, initialState } from './game-details.reducer';

const mutateState = mergeRight(initialState) as (data: Partial<GameDetailsState>) => GameDetailsState;

describe('GameDetails Reducer', () => {
  describe('unknown action', () => {
    it('should return the initial state', () => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const action = {} as any;

      const result = gameDetailsReducer(initialState, action);

      expect(result).toBe(initialState);
    });
  });
  describe('ChangeLevelTypeAction', () => {
    it('should change the level type', () => {
      const action = GAME_DETAILS_ACTIONS.changeLevelType({ level: 2, levelType: 4 });
      const mutatedState = mutateState({
        levels: mockedGameDetails.stat.Levels,
      });
      const expectedState = mutateState({
        levels: [
          {
            level: 1,
            name: 'Старт',
            position: 0,
            type: 0,
            removed: false,
          },
          {
            level: 2,
            name: 'авангард',
            position: 1,
            type: 4,
            removed: false,
          },
          {
            level: 3,
            name: 'пошук на авангарді',
            position: 2,
            type: 1,
            removed: false,
          },
          {
            level: 4,
            name: 'агентський',
            position: 3,
            type: 4,
            removed: false,
          },
          {
            level: 5,
            name: 'Військомат',
            position: 4,
            type: 0,
            removed: true,
          },
          {
            level: 6,
            name: 'чорновола',
            position: 5,
            type: 0,
            removed: false,
          },
          {
            level: 7,
            name: '24 з 26 Парк',
            position: 6,
            type: 0,
            removed: false,
          },
          {
            level: 8,
            name: 'Поштова 5',
            position: 7,
            type: 0,
            removed: false,
          },
          {
            level: 9,
            name: 'Міцкевича і Пушкына',
            position: 8,
            type: 0,
            removed: false,
          },
          {
            level: 10,
            name: 'Логіка',
            position: 9,
            type: 2,
            removed: false,
          },
          {
            level: 11,
            name: 'Кавказька і набережна',
            position: 10,
            type: 0,
            removed: false,
          },
          {
            level: 12,
            name: 'Пошук Олімп',
            position: 11,
            type: 1,
            removed: false,
          },
          {
            level: 13,
            name: 'Перший промінь',
            position: 12,
            type: 0,
            removed: false,
          },
          {
            level: 14,
            name: 'Текстильник',
            position: 13,
            type: 0,
            removed: false,
          },
          {
            level: 15,
            name: 'Нова',
            position: 14,
            type: 0,
            removed: false,
          },
          {
            level: 16,
            name: 'Тайм-аут -',
            position: 15,
            type: 0,
            removed: false,
          },
          {
            level: 17,
            name: 'Транспортна і вовчка',
            position: 16,
            type: 0,
            removed: false,
          },
          {
            level: 18,
            name: 'Майдан Перемоги',
            position: 17,
            type: 0,
            removed: false,
          },
          {
            level: 19,
            name: 'Доїзд фініш',
            position: 18,
            type: 3,
            removed: false,
          },
          {
            level: 20,
            name: 'Фініш',
            position: 19,
            type: 0,
            removed: false,
          },
          {
            level: 'Итоговое время',
            name: 'Итоговое время',
            position: 20,
            type: 0,
            removed: false,
          },
        ],
      });
      const resultedState = gameDetailsReducer(mutatedState, action);
      expect(resultedState).toEqual(expectedState);
    });
  });
  describe('CleanGameDataAction', () => {
    it('should return initial state', () => {
      const action = GAME_DETAILS_ACTIONS.cleanGameData();
      const mutatedState = mutateState({
        isLoading: false,
        gameInfo: {
          GameId: 66344,
          FinishTime: '2019-09-29T03:00:00.000Z',
          GameName: 'Qliga: "Ghostbusters" (Этап лиги квеста 2019, в г. Харьков)',
          Domain: 'quest.ua',
          StartTime: '2019-09-27T17:08:00.000Z',
          Timezone: '+03:00',
        },
      });
      const resultedState = gameDetailsReducer(mutatedState, action);
      expect(resultedState).toEqual(initialState);
    });
  });
  describe('ChangeTotalStatTabAction', () => {
    it('should return initial state', () => {
      const action = GAME_DETAILS_ACTIONS.changeTotalStatTab({ tab: 1 });
      const mutatedState = mutateState({
        selectedTotalTab: 0,
      });
      const expectedState = mutateState({
        selectedTotalTab: 1,
      });
      const resultedState = gameDetailsReducer(mutatedState, action);
      expect(resultedState).toEqual(expectedState);
    });
  });
  describe('GetLatestDataFromEnAction', () => {
    it('should clean the existed data', () => {
      const action = GAME_DETAILS_ACTIONS.getLatestDataFromEn();
      const mutatedState = mutateState({
        levels: mockedGameDetails.stat.Levels,
        dataByTeam: mockedGameDetails.stat.DataByTeam,
        dataByLevels: mockedGameDetails.stat.DataByLevels,
        finishResults: mockedGameDetails.stat.FinishResults,
        originalLevels: mockedGameDetails.stat.Levels,
      });
      const expectedState = mutateState({
        levels: [],
        dataByTeam: [],
        dataByLevels: [],
        finishResults: [],
        originalLevels: [],
      });
      const resultedState = gameDetailsReducer(mutatedState, action);
      expect(expectedState).toEqual(resultedState);
    });
  });
  describe('RemoveLevelFromStatAction', () => {
    it('should recalculate data if level is removed', () => {
      const action = GAME_DETAILS_ACTIONS.removeLevelFromState({ removed: true, level: 2 });
      const mutatedState = mutateState({
        levels: mockedGameDetails.stat.Levels,
        dataByTeam: mockedGameDetails.stat.DataByTeam,
        dataByLevels: mockedGameDetails.stat.DataByLevels,
        finishResults: mockedGameDetails.stat.FinishResults,
      });
      const expectedState = mutateState({
        levels: [
          {
            level: 1,
            name: 'Старт',
            position: 0,
            type: 0,
            removed: false,
          },
          {
            level: 2,
            name: 'авангард',
            position: 1,
            type: 0,
            removed: true,
          },
          {
            level: 3,
            name: 'пошук на авангарді',
            position: 2,
            type: 1,
            removed: false,
          },
          {
            level: 4,
            name: 'агентський',
            position: 3,
            type: 4,
            removed: false,
          },
          {
            level: 5,
            name: 'Військомат',
            position: 4,
            type: 0,
            removed: true,
          },
          {
            level: 6,
            name: 'чорновола',
            position: 5,
            type: 0,
            removed: false,
          },
          {
            level: 7,
            name: '24 з 26 Парк',
            position: 6,
            type: 0,
            removed: false,
          },
          {
            level: 8,
            name: 'Поштова 5',
            position: 7,
            type: 0,
            removed: false,
          },
          {
            level: 9,
            name: 'Міцкевича і Пушкына',
            position: 8,
            type: 0,
            removed: false,
          },
          {
            level: 10,
            name: 'Логіка',
            position: 9,
            type: 2,
            removed: false,
          },
          {
            level: 11,
            name: 'Кавказька і набережна',
            position: 10,
            type: 0,
            removed: false,
          },
          {
            level: 12,
            name: 'Пошук Олімп',
            position: 11,
            type: 1,
            removed: false,
          },
          {
            level: 13,
            name: 'Перший промінь',
            position: 12,
            type: 0,
            removed: false,
          },
          {
            level: 14,
            name: 'Текстильник',
            position: 13,
            type: 0,
            removed: false,
          },
          {
            level: 15,
            name: 'Нова',
            position: 14,
            type: 0,
            removed: false,
          },
          {
            level: 16,
            name: 'Тайм-аут -',
            position: 15,
            type: 0,
            removed: false,
          },
          {
            level: 17,
            name: 'Транспортна і вовчка',
            position: 16,
            type: 0,
            removed: false,
          },
          {
            level: 18,
            name: 'Майдан Перемоги',
            position: 17,
            type: 0,
            removed: false,
          },
          {
            level: 19,
            name: 'Доїзд фініш',
            position: 18,
            type: 3,
            removed: false,
          },
          {
            level: 20,
            name: 'Фініш',
            position: 19,
            type: 0,
            removed: false,
          },
          {
            level: 'Итоговое время',
            name: 'Итоговое время',
            position: 20,
            type: 0,
            removed: false,
          },
        ],
        dataByTeam: [
          {
            id: 13977,
            data: [
              {
                id: 13977,
                levelIdx: 0,
                name: 'Закон Ома',
                levelTime: '2017-12-01T19:24:56+01:00',
                additionsTime: null,
                timeout: false,
                duration: 296000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 1,
                name: 'Закон Ома',
                levelTime: '2017-12-01T19:30:15+01:00',
                additionsTime: 319000,
                timeout: false,
                duration: 319000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 2,
                name: 'Закон Ома',
                levelTime: '2017-12-01T19:43:13+01:00',
                additionsTime: null,
                timeout: false,
                duration: 778000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 3,
                name: 'Закон Ома',
                levelTime: '2017-12-01T19:45:36+01:00',
                additionsTime: null,
                timeout: false,
                duration: 143000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 4,
                name: 'Закон Ома',
                levelTime: '2017-12-01T19:57:21+01:00',
                additionsTime: 705000,
                timeout: false,
                duration: 705000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 5,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:12:25+01:00',
                additionsTime: null,
                timeout: false,
                duration: 904000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 6,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:14:40+01:00',
                additionsTime: null,
                timeout: false,
                duration: 135000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 7,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:17:15+01:00',
                additionsTime: null,
                timeout: false,
                duration: 155000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 8,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:24:13+01:00',
                additionsTime: null,
                timeout: false,
                duration: 418000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 9,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:24:57+01:00',
                additionsTime: null,
                timeout: false,
                duration: 44000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 10,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:29:06+01:00',
                additionsTime: null,
                timeout: false,
                duration: 249000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 11,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:44:58+01:00',
                additionsTime: null,
                timeout: false,
                duration: 952000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 12,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:56:27+01:00',
                additionsTime: null,
                timeout: false,
                duration: 689000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 13,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:00:44+01:00',
                additionsTime: null,
                timeout: false,
                duration: 257000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 14,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:03:08+01:00',
                additionsTime: null,
                timeout: false,
                duration: 144000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 15,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:05:50+01:00',
                additionsTime: null,
                timeout: false,
                duration: 162000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 16,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:09:15+01:00',
                additionsTime: null,
                timeout: false,
                duration: 205000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 17,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:17:35+01:00',
                additionsTime: null,
                timeout: false,
                duration: 500000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 18,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:21:09+01:00',
                additionsTime: null,
                timeout: false,
                duration: 214000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 19,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:23:09+01:00',
                additionsTime: null,
                timeout: true,
                duration: 120000,
                bestTime: false,
              },
            ],
          },
          {
            id: 140550,
            data: [
              {
                id: 140550,
                levelIdx: 0,
                name: 'Tachky',
                levelTime: '2017-12-01T19:24:35+01:00',
                additionsTime: null,
                timeout: false,
                duration: 275000,
                bestTime: true,
              },
              {
                id: 140550,
                levelIdx: 1,
                name: 'Tachky',
                levelTime: '2017-12-01T19:27:45+01:00',
                additionsTime: 190000,
                timeout: false,
                duration: 190000,
                bestTime: true,
              },
              {
                id: 140550,
                levelIdx: 2,
                name: 'Tachky',
                levelTime: '2017-12-01T19:32:45+01:00',
                additionsTime: null,
                timeout: false,
                duration: 300000,
                bestTime: true,
              },
              {
                id: 140550,
                levelIdx: 3,
                name: 'Tachky',
                levelTime: '2017-12-01T19:38:43+01:00',
                additionsTime: null,
                timeout: false,
                duration: 358000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 4,
                name: 'Tachky',
                levelTime: '2017-12-01T19:57:04+01:00',
                additionsTime: 1101000,
                timeout: false,
                duration: 1101000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 5,
                name: 'Tachky',
                levelTime: '2017-12-01T20:14:50+01:00',
                additionsTime: null,
                timeout: false,
                duration: 1066000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 6,
                name: 'Tachky',
                levelTime: '2017-12-01T20:17:37+01:00',
                additionsTime: null,
                timeout: false,
                duration: 167000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 7,
                name: 'Tachky',
                levelTime: '2017-12-01T20:30:15+01:00',
                additionsTime: null,
                timeout: false,
                duration: 758000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 8,
                name: 'Tachky',
                levelTime: '2017-12-01T20:39:31+01:00',
                additionsTime: null,
                timeout: false,
                duration: 556000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 9,
                name: 'Tachky',
                levelTime: '2017-12-01T20:41:17+01:00',
                additionsTime: null,
                timeout: false,
                duration: 106000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 10,
                name: 'Tachky',
                levelTime: '2017-12-01T20:44:25+01:00',
                additionsTime: null,
                timeout: false,
                duration: 188000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 11,
                name: 'Tachky',
                levelTime: '2017-12-01T20:57:52+01:00',
                additionsTime: null,
                timeout: false,
                duration: 807000,
                bestTime: true,
              },
              {
                id: 140550,
                levelIdx: 12,
                name: 'Tachky',
                levelTime: '2017-12-01T21:03:42+01:00',
                additionsTime: null,
                timeout: false,
                duration: 350000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 13,
                name: 'Tachky',
                levelTime: '2017-12-01T21:22:16+01:00',
                additionsTime: null,
                timeout: false,
                duration: 1114000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 14,
                name: 'Tachky',
                levelTime: '2017-12-01T21:25:46+01:00',
                additionsTime: null,
                timeout: false,
                duration: 210000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 15,
                name: 'Tachky',
                levelTime: '2017-12-01T21:27:19+01:00',
                additionsTime: null,
                timeout: false,
                duration: 93000,
                bestTime: true,
              },
              {
                id: 140550,
                levelIdx: 16,
                name: 'Tachky',
                levelTime: '2017-12-01T21:33:36+01:00',
                additionsTime: null,
                timeout: false,
                duration: 377000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 17,
                name: 'Tachky',
                levelTime: '2017-12-01T21:46:03+01:00',
                additionsTime: null,
                timeout: false,
                duration: 747000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 18,
                name: 'Tachky',
                levelTime: '2017-12-01T21:52:00+01:00',
                additionsTime: null,
                timeout: false,
                duration: 357000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 19,
                name: 'Tachky',
                levelTime: '2017-12-01T21:54:00+01:00',
                additionsTime: null,
                timeout: true,
                duration: 120000,
                bestTime: false,
              },
            ],
          },
          {
            id: 154808,
            data: [
              {
                id: 154808,
                levelIdx: 0,
                name: 'Dream team best',
                levelTime: '2017-12-01T19:24:37+01:00',
                additionsTime: null,
                timeout: false,
                duration: 277000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 1,
                name: 'Dream team best',
                levelTime: '2017-12-01T19:29:45+01:00',
                additionsTime: 308000,
                timeout: false,
                duration: 308000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 2,
                name: 'Dream team best',
                levelTime: '2017-12-01T19:51:45+01:00',
                additionsTime: null,
                timeout: true,
                duration: 1320000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 3,
                name: 'Dream team best',
                levelTime: '2017-12-01T19:54:10+01:00',
                additionsTime: null,
                timeout: false,
                duration: 145000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 4,
                name: 'Dream team best',
                levelTime: '2017-12-01T19:57:10+01:00',
                additionsTime: 180000,
                timeout: false,
                duration: 180000,
                bestTime: true,
              },
              {
                id: 154808,
                levelIdx: 5,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:04:03+01:00',
                additionsTime: null,
                timeout: false,
                duration: 413000,
                bestTime: true,
              },
              {
                id: 154808,
                levelIdx: 6,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:07:28+01:00',
                additionsTime: null,
                timeout: false,
                duration: 205000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 7,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:16:13+01:00',
                additionsTime: null,
                timeout: false,
                duration: 525000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 8,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:31:37+01:00',
                additionsTime: null,
                timeout: false,
                duration: 924000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 9,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:33:01+01:00',
                additionsTime: null,
                timeout: false,
                duration: 84000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 10,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:34:47+01:00',
                additionsTime: null,
                timeout: false,
                duration: 106000,
                bestTime: true,
              },
              {
                id: 154808,
                levelIdx: 11,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:49:42+01:00',
                additionsTime: null,
                timeout: false,
                duration: 895000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 12,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:53:31+01:00',
                additionsTime: null,
                timeout: false,
                duration: 229000,
                bestTime: true,
              },
              {
                id: 154808,
                levelIdx: 13,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:58:28+01:00',
                additionsTime: null,
                timeout: false,
                duration: 297000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 14,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:01:53+01:00',
                additionsTime: null,
                timeout: false,
                duration: 205000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 15,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:03:58+01:00',
                additionsTime: null,
                timeout: false,
                duration: 125000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 16,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:09:32+01:00',
                additionsTime: null,
                timeout: false,
                duration: 334000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 17,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:19:36+01:00',
                additionsTime: null,
                timeout: false,
                duration: 604000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 18,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:21:58+01:00',
                additionsTime: null,
                timeout: false,
                duration: 142000,
                bestTime: true,
              },
              {
                id: 154808,
                levelIdx: 19,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:23:58+01:00',
                additionsTime: null,
                timeout: true,
                duration: 120000,
                bestTime: false,
              },
            ],
          },
        ],
        dataByLevels: [
          [
            {
              id: 140550,
              levelIdx: 0,
              name: 'Tachky',
              levelTime: '2017-12-01T19:24:35+01:00',
              additionsTime: null,
              timeout: false,
              duration: 275000,
              bestTime: true,
            },
            {
              id: 140550,
              levelIdx: 1,
              name: 'Tachky',
              levelTime: '2017-12-01T19:27:45+01:00',
              additionsTime: 190000,
              timeout: false,
              duration: 190000,
              bestTime: true,
            },
            {
              id: 140550,
              levelIdx: 2,
              name: 'Tachky',
              levelTime: '2017-12-01T19:32:45+01:00',
              additionsTime: null,
              timeout: false,
              duration: 300000,
              bestTime: true,
            },
            {
              id: 140550,
              levelIdx: 3,
              name: 'Tachky',
              levelTime: '2017-12-01T19:38:43+01:00',
              additionsTime: null,
              timeout: false,
              duration: 358000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 4,
              name: 'Tachky',
              levelTime: '2017-12-01T19:57:04+01:00',
              additionsTime: 1101000,
              timeout: false,
              duration: 1101000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 5,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:04:03+01:00',
              additionsTime: null,
              timeout: false,
              duration: 413000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 6,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:07:28+01:00',
              additionsTime: null,
              timeout: false,
              duration: 205000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 7,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:16:13+01:00',
              additionsTime: null,
              timeout: false,
              duration: 525000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 8,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:24:13+01:00',
              additionsTime: null,
              timeout: false,
              duration: 418000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 9,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:24:57+01:00',
              additionsTime: null,
              timeout: false,
              duration: 44000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 10,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:29:06+01:00',
              additionsTime: null,
              timeout: false,
              duration: 249000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 11,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:44:58+01:00',
              additionsTime: null,
              timeout: false,
              duration: 952000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 12,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:53:31+01:00',
              additionsTime: null,
              timeout: false,
              duration: 229000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 13,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:58:28+01:00',
              additionsTime: null,
              timeout: false,
              duration: 297000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 14,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:01:53+01:00',
              additionsTime: null,
              timeout: false,
              duration: 205000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 15,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:03:58+01:00',
              additionsTime: null,
              timeout: false,
              duration: 125000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 16,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:09:15+01:00',
              additionsTime: null,
              timeout: false,
              duration: 205000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 17,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:17:35+01:00',
              additionsTime: null,
              timeout: false,
              duration: 500000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 18,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:21:09+01:00',
              additionsTime: null,
              timeout: false,
              duration: 214000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 19,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:23:09+01:00',
              additionsTime: null,
              timeout: true,
              duration: 120000,
              bestTime: false,
            },
          ],
          [
            {
              id: 154808,
              levelIdx: 0,
              name: 'Dream team best',
              levelTime: '2017-12-01T19:24:37+01:00',
              additionsTime: null,
              timeout: false,
              duration: 277000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 1,
              name: 'Dream team best',
              levelTime: '2017-12-01T19:29:45+01:00',
              additionsTime: 308000,
              timeout: false,
              duration: 308000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 2,
              name: 'Закон Ома',
              levelTime: '2017-12-01T19:43:13+01:00',
              additionsTime: null,
              timeout: false,
              duration: 778000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 3,
              name: 'Закон Ома',
              levelTime: '2017-12-01T19:45:36+01:00',
              additionsTime: null,
              timeout: false,
              duration: 143000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 4,
              name: 'Dream team best',
              levelTime: '2017-12-01T19:57:10+01:00',
              additionsTime: 180000,
              timeout: false,
              duration: 180000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 5,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:12:25+01:00',
              additionsTime: null,
              timeout: false,
              duration: 904000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 6,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:14:40+01:00',
              additionsTime: null,
              timeout: false,
              duration: 135000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 7,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:17:15+01:00',
              additionsTime: null,
              timeout: false,
              duration: 155000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 8,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:31:37+01:00',
              additionsTime: null,
              timeout: false,
              duration: 924000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 9,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:33:01+01:00',
              additionsTime: null,
              timeout: false,
              duration: 84000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 10,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:34:47+01:00',
              additionsTime: null,
              timeout: false,
              duration: 106000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 11,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:49:42+01:00',
              additionsTime: null,
              timeout: false,
              duration: 895000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 12,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:56:27+01:00',
              additionsTime: null,
              timeout: false,
              duration: 689000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 13,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:00:44+01:00',
              additionsTime: null,
              timeout: false,
              duration: 257000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 14,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:03:08+01:00',
              additionsTime: null,
              timeout: false,
              duration: 144000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 15,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:05:50+01:00',
              additionsTime: null,
              timeout: false,
              duration: 162000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 16,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:09:32+01:00',
              additionsTime: null,
              timeout: false,
              duration: 334000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 17,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:19:36+01:00',
              additionsTime: null,
              timeout: false,
              duration: 604000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 18,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:21:58+01:00',
              additionsTime: null,
              timeout: false,
              duration: 142000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 19,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:23:58+01:00',
              additionsTime: null,
              timeout: true,
              duration: 120000,
              bestTime: false,
            },
          ],
          [
            {
              id: 13977,
              levelIdx: 0,
              name: 'Закон Ома',
              levelTime: '2017-12-01T19:24:56+01:00',
              additionsTime: null,
              timeout: false,
              duration: 296000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 1,
              name: 'Закон Ома',
              levelTime: '2017-12-01T19:30:15+01:00',
              additionsTime: 319000,
              timeout: false,
              duration: 319000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 2,
              name: 'Dream team best',
              levelTime: '2017-12-01T19:51:45+01:00',
              additionsTime: null,
              timeout: true,
              duration: 1320000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 3,
              name: 'Dream team best',
              levelTime: '2017-12-01T19:54:10+01:00',
              additionsTime: null,
              timeout: false,
              duration: 145000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 4,
              name: 'Закон Ома',
              levelTime: '2017-12-01T19:57:21+01:00',
              additionsTime: 705000,
              timeout: false,
              duration: 705000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 5,
              name: 'Tachky',
              levelTime: '2017-12-01T20:14:50+01:00',
              additionsTime: null,
              timeout: false,
              duration: 1066000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 6,
              name: 'Tachky',
              levelTime: '2017-12-01T20:17:37+01:00',
              additionsTime: null,
              timeout: false,
              duration: 167000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 7,
              name: 'Tachky',
              levelTime: '2017-12-01T20:30:15+01:00',
              additionsTime: null,
              timeout: false,
              duration: 758000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 8,
              name: 'Tachky',
              levelTime: '2017-12-01T20:39:31+01:00',
              additionsTime: null,
              timeout: false,
              duration: 556000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 9,
              name: 'Tachky',
              levelTime: '2017-12-01T20:41:17+01:00',
              additionsTime: null,
              timeout: false,
              duration: 106000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 10,
              name: 'Tachky',
              levelTime: '2017-12-01T20:44:25+01:00',
              additionsTime: null,
              timeout: false,
              duration: 188000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 11,
              name: 'Tachky',
              levelTime: '2017-12-01T20:57:52+01:00',
              additionsTime: null,
              timeout: false,
              duration: 807000,
              bestTime: true,
            },
            {
              id: 140550,
              levelIdx: 12,
              name: 'Tachky',
              levelTime: '2017-12-01T21:03:42+01:00',
              additionsTime: null,
              timeout: false,
              duration: 350000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 13,
              name: 'Tachky',
              levelTime: '2017-12-01T21:22:16+01:00',
              additionsTime: null,
              timeout: false,
              duration: 1114000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 14,
              name: 'Tachky',
              levelTime: '2017-12-01T21:25:46+01:00',
              additionsTime: null,
              timeout: false,
              duration: 210000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 15,
              name: 'Tachky',
              levelTime: '2017-12-01T21:27:19+01:00',
              additionsTime: null,
              timeout: false,
              duration: 93000,
              bestTime: true,
            },
            {
              id: 140550,
              levelIdx: 16,
              name: 'Tachky',
              levelTime: '2017-12-01T21:33:36+01:00',
              additionsTime: null,
              timeout: false,
              duration: 377000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 17,
              name: 'Tachky',
              levelTime: '2017-12-01T21:46:03+01:00',
              additionsTime: null,
              timeout: false,
              duration: 747000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 18,
              name: 'Tachky',
              levelTime: '2017-12-01T21:52:00+01:00',
              additionsTime: null,
              timeout: false,
              duration: 357000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 19,
              name: 'Tachky',
              levelTime: '2017-12-01T21:54:00+01:00',
              additionsTime: null,
              timeout: true,
              duration: 120000,
              bestTime: false,
            },
          ],
        ],
        finishResults: [
          {
            id: 13977,
            levelIdx: null,
            name: 'Закон Ома',
            levelTime: '2017-12-01T21:23:09+01:00',
            additionsTime: 1024000,
            timeout: false,
            duration: 7389000,
            extraBonus: 0,
            closedLevels: 20,
          },
          {
            id: 154808,
            levelIdx: null,
            name: 'Dream team best',
            levelTime: '2017-12-01T21:23:58+01:00',
            additionsTime: 488000,
            timeout: false,
            duration: 7438000,
            extraBonus: 0,
            closedLevels: 20,
          },
          {
            id: 140550,
            levelIdx: null,
            name: 'Tachky',
            levelTime: '2017-12-01T21:54:00+01:00',
            additionsTime: 1291000,
            timeout: false,
            duration: 9240000,
            extraBonus: 0,
            closedLevels: 20,
          },
        ],
      });
      const resultedState = gameDetailsReducer(mutatedState, action);
      expect(expectedState).toEqual(resultedState);
    });
    it('should recalculate data if level is restored', () => {
      const action = GAME_DETAILS_ACTIONS.removeLevelFromState({ removed: false, level: 4 });
      const mutatedState = mutateState({
        levels: mockedGameDetails.stat.Levels,
        dataByTeam: mockedGameDetails.stat.DataByTeam,
        dataByLevels: mockedGameDetails.stat.DataByLevels,
        finishResults: mockedGameDetails.stat.FinishResults,
      });
      const expectedState = mutateState({
        levels: [
          {
            level: 1,
            name: 'Старт',
            position: 0,
            type: 0,
            removed: false,
          },
          {
            level: 2,
            name: 'авангард',
            position: 1,
            type: 0,
            removed: false,
          },
          {
            level: 3,
            name: 'пошук на авангарді',
            position: 2,
            type: 1,
            removed: false,
          },
          {
            level: 4,
            name: 'агентський',
            position: 3,
            type: 4,
            removed: false,
          },
          {
            level: 5,
            name: 'Військомат',
            position: 4,
            type: 0,
            removed: true,
          },
          {
            level: 6,
            name: 'чорновола',
            position: 5,
            type: 0,
            removed: false,
          },
          {
            level: 7,
            name: '24 з 26 Парк',
            position: 6,
            type: 0,
            removed: false,
          },
          {
            level: 8,
            name: 'Поштова 5',
            position: 7,
            type: 0,
            removed: false,
          },
          {
            level: 9,
            name: 'Міцкевича і Пушкына',
            position: 8,
            type: 0,
            removed: false,
          },
          {
            level: 10,
            name: 'Логіка',
            position: 9,
            type: 2,
            removed: false,
          },
          {
            level: 11,
            name: 'Кавказька і набережна',
            position: 10,
            type: 0,
            removed: false,
          },
          {
            level: 12,
            name: 'Пошук Олімп',
            position: 11,
            type: 1,
            removed: false,
          },
          {
            level: 13,
            name: 'Перший промінь',
            position: 12,
            type: 0,
            removed: false,
          },
          {
            level: 14,
            name: 'Текстильник',
            position: 13,
            type: 0,
            removed: false,
          },
          {
            level: 15,
            name: 'Нова',
            position: 14,
            type: 0,
            removed: false,
          },
          {
            level: 16,
            name: 'Тайм-аут -',
            position: 15,
            type: 0,
            removed: false,
          },
          {
            level: 17,
            name: 'Транспортна і вовчка',
            position: 16,
            type: 0,
            removed: false,
          },
          {
            level: 18,
            name: 'Майдан Перемоги',
            position: 17,
            type: 0,
            removed: false,
          },
          {
            level: 19,
            name: 'Доїзд фініш',
            position: 18,
            type: 3,
            removed: false,
          },
          {
            level: 20,
            name: 'Фініш',
            position: 19,
            type: 0,
            removed: false,
          },
          {
            level: 'Итоговое время',
            name: 'Итоговое время',
            position: 20,
            type: 0,
            removed: false,
          },
        ],
        dataByTeam: [
          {
            id: 13977,
            data: [
              {
                id: 13977,
                levelIdx: 0,
                name: 'Закон Ома',
                levelTime: '2017-12-01T19:24:56+01:00',
                additionsTime: null,
                timeout: false,
                duration: 296000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 1,
                name: 'Закон Ома',
                levelTime: '2017-12-01T19:30:15+01:00',
                additionsTime: null,
                timeout: false,
                duration: 319000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 2,
                name: 'Закон Ома',
                levelTime: '2017-12-01T19:43:13+01:00',
                additionsTime: null,
                timeout: false,
                duration: 778000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 3,
                name: 'Закон Ома',
                levelTime: '2017-12-01T19:45:36+01:00',
                additionsTime: -143000,
                timeout: false,
                duration: 143000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 4,
                name: 'Закон Ома',
                levelTime: '2017-12-01T19:57:21+01:00',
                additionsTime: 705000,
                timeout: false,
                duration: 705000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 5,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:12:25+01:00',
                additionsTime: null,
                timeout: false,
                duration: 904000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 6,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:14:40+01:00',
                additionsTime: null,
                timeout: false,
                duration: 135000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 7,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:17:15+01:00',
                additionsTime: null,
                timeout: false,
                duration: 155000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 8,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:24:13+01:00',
                additionsTime: null,
                timeout: false,
                duration: 418000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 9,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:24:57+01:00',
                additionsTime: null,
                timeout: false,
                duration: 44000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 10,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:29:06+01:00',
                additionsTime: null,
                timeout: false,
                duration: 249000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 11,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:44:58+01:00',
                additionsTime: null,
                timeout: false,
                duration: 952000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 12,
                name: 'Закон Ома',
                levelTime: '2017-12-01T20:56:27+01:00',
                additionsTime: null,
                timeout: false,
                duration: 689000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 13,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:00:44+01:00',
                additionsTime: null,
                timeout: false,
                duration: 257000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 14,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:03:08+01:00',
                additionsTime: null,
                timeout: false,
                duration: 144000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 15,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:05:50+01:00',
                additionsTime: null,
                timeout: false,
                duration: 162000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 16,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:09:15+01:00',
                additionsTime: null,
                timeout: false,
                duration: 205000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 17,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:17:35+01:00',
                additionsTime: null,
                timeout: false,
                duration: 500000,
                bestTime: true,
              },
              {
                id: 13977,
                levelIdx: 18,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:21:09+01:00',
                additionsTime: null,
                timeout: false,
                duration: 214000,
                bestTime: false,
              },
              {
                id: 13977,
                levelIdx: 19,
                name: 'Закон Ома',
                levelTime: '2017-12-01T21:23:09+01:00',
                additionsTime: null,
                timeout: true,
                duration: 120000,
                bestTime: false,
              },
            ],
          },
          {
            id: 140550,
            data: [
              {
                id: 140550,
                levelIdx: 0,
                name: 'Tachky',
                levelTime: '2017-12-01T19:24:35+01:00',
                additionsTime: null,
                timeout: false,
                duration: 275000,
                bestTime: true,
              },
              {
                id: 140550,
                levelIdx: 1,
                name: 'Tachky',
                levelTime: '2017-12-01T19:27:45+01:00',
                additionsTime: null,
                timeout: false,
                duration: 190000,
                bestTime: true,
              },
              {
                id: 140550,
                levelIdx: 2,
                name: 'Tachky',
                levelTime: '2017-12-01T19:32:45+01:00',
                additionsTime: null,
                timeout: false,
                duration: 300000,
                bestTime: true,
              },
              {
                id: 140550,
                levelIdx: 3,
                name: 'Tachky',
                levelTime: '2017-12-01T19:38:43+01:00',
                additionsTime: -358000,
                timeout: false,
                duration: 358000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 4,
                name: 'Tachky',
                levelTime: '2017-12-01T19:57:04+01:00',
                additionsTime: 1101000,
                timeout: false,
                duration: 1101000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 5,
                name: 'Tachky',
                levelTime: '2017-12-01T20:14:50+01:00',
                additionsTime: null,
                timeout: false,
                duration: 1066000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 6,
                name: 'Tachky',
                levelTime: '2017-12-01T20:17:37+01:00',
                additionsTime: null,
                timeout: false,
                duration: 167000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 7,
                name: 'Tachky',
                levelTime: '2017-12-01T20:30:15+01:00',
                additionsTime: null,
                timeout: false,
                duration: 758000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 8,
                name: 'Tachky',
                levelTime: '2017-12-01T20:39:31+01:00',
                additionsTime: null,
                timeout: false,
                duration: 556000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 9,
                name: 'Tachky',
                levelTime: '2017-12-01T20:41:17+01:00',
                additionsTime: null,
                timeout: false,
                duration: 106000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 10,
                name: 'Tachky',
                levelTime: '2017-12-01T20:44:25+01:00',
                additionsTime: null,
                timeout: false,
                duration: 188000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 11,
                name: 'Tachky',
                levelTime: '2017-12-01T20:57:52+01:00',
                additionsTime: null,
                timeout: false,
                duration: 807000,
                bestTime: true,
              },
              {
                id: 140550,
                levelIdx: 12,
                name: 'Tachky',
                levelTime: '2017-12-01T21:03:42+01:00',
                additionsTime: null,
                timeout: false,
                duration: 350000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 13,
                name: 'Tachky',
                levelTime: '2017-12-01T21:22:16+01:00',
                additionsTime: null,
                timeout: false,
                duration: 1114000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 14,
                name: 'Tachky',
                levelTime: '2017-12-01T21:25:46+01:00',
                additionsTime: null,
                timeout: false,
                duration: 210000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 15,
                name: 'Tachky',
                levelTime: '2017-12-01T21:27:19+01:00',
                additionsTime: null,
                timeout: false,
                duration: 93000,
                bestTime: true,
              },
              {
                id: 140550,
                levelIdx: 16,
                name: 'Tachky',
                levelTime: '2017-12-01T21:33:36+01:00',
                additionsTime: null,
                timeout: false,
                duration: 377000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 17,
                name: 'Tachky',
                levelTime: '2017-12-01T21:46:03+01:00',
                additionsTime: null,
                timeout: false,
                duration: 747000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 18,
                name: 'Tachky',
                levelTime: '2017-12-01T21:52:00+01:00',
                additionsTime: null,
                timeout: false,
                duration: 357000,
                bestTime: false,
              },
              {
                id: 140550,
                levelIdx: 19,
                name: 'Tachky',
                levelTime: '2017-12-01T21:54:00+01:00',
                additionsTime: null,
                timeout: true,
                duration: 120000,
                bestTime: false,
              },
            ],
          },
          {
            id: 154808,
            data: [
              {
                id: 154808,
                levelIdx: 0,
                name: 'Dream team best',
                levelTime: '2017-12-01T19:24:37+01:00',
                additionsTime: null,
                timeout: false,
                duration: 277000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 1,
                name: 'Dream team best',
                levelTime: '2017-12-01T19:29:45+01:00',
                additionsTime: null,
                timeout: false,
                duration: 308000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 2,
                name: 'Dream team best',
                levelTime: '2017-12-01T19:51:45+01:00',
                additionsTime: null,
                timeout: true,
                duration: 1320000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 3,
                name: 'Dream team best',
                levelTime: '2017-12-01T19:54:10+01:00',
                additionsTime: -145000,
                timeout: false,
                duration: 145000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 4,
                name: 'Dream team best',
                levelTime: '2017-12-01T19:57:10+01:00',
                additionsTime: 180000,
                timeout: false,
                duration: 180000,
                bestTime: true,
              },
              {
                id: 154808,
                levelIdx: 5,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:04:03+01:00',
                additionsTime: null,
                timeout: false,
                duration: 413000,
                bestTime: true,
              },
              {
                id: 154808,
                levelIdx: 6,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:07:28+01:00',
                additionsTime: null,
                timeout: false,
                duration: 205000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 7,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:16:13+01:00',
                additionsTime: null,
                timeout: false,
                duration: 525000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 8,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:31:37+01:00',
                additionsTime: null,
                timeout: false,
                duration: 924000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 9,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:33:01+01:00',
                additionsTime: null,
                timeout: false,
                duration: 84000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 10,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:34:47+01:00',
                additionsTime: null,
                timeout: false,
                duration: 106000,
                bestTime: true,
              },
              {
                id: 154808,
                levelIdx: 11,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:49:42+01:00',
                additionsTime: null,
                timeout: false,
                duration: 895000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 12,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:53:31+01:00',
                additionsTime: null,
                timeout: false,
                duration: 229000,
                bestTime: true,
              },
              {
                id: 154808,
                levelIdx: 13,
                name: 'Dream team best',
                levelTime: '2017-12-01T20:58:28+01:00',
                additionsTime: null,
                timeout: false,
                duration: 297000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 14,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:01:53+01:00',
                additionsTime: null,
                timeout: false,
                duration: 205000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 15,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:03:58+01:00',
                additionsTime: null,
                timeout: false,
                duration: 125000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 16,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:09:32+01:00',
                additionsTime: null,
                timeout: false,
                duration: 334000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 17,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:19:36+01:00',
                additionsTime: null,
                timeout: false,
                duration: 604000,
                bestTime: false,
              },
              {
                id: 154808,
                levelIdx: 18,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:21:58+01:00',
                additionsTime: null,
                timeout: false,
                duration: 142000,
                bestTime: true,
              },
              {
                id: 154808,
                levelIdx: 19,
                name: 'Dream team best',
                levelTime: '2017-12-01T21:23:58+01:00',
                additionsTime: null,
                timeout: true,
                duration: 120000,
                bestTime: false,
              },
            ],
          },
        ],
        dataByLevels: [
          [
            {
              id: 140550,
              levelIdx: 0,
              name: 'Tachky',
              levelTime: '2017-12-01T19:24:35+01:00',
              additionsTime: null,
              timeout: false,
              duration: 275000,
              bestTime: true,
            },
            {
              id: 140550,
              levelIdx: 1,
              name: 'Tachky',
              levelTime: '2017-12-01T19:27:45+01:00',
              additionsTime: null,
              timeout: false,
              duration: 190000,
              bestTime: true,
            },
            {
              id: 140550,
              levelIdx: 2,
              name: 'Tachky',
              levelTime: '2017-12-01T19:32:45+01:00',
              additionsTime: null,
              timeout: false,
              duration: 300000,
              bestTime: true,
            },
            {
              id: 140550,
              levelIdx: 3,
              name: 'Tachky',
              levelTime: '2017-12-01T19:38:43+01:00',
              additionsTime: -358000,
              timeout: false,
              duration: 358000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 4,
              name: 'Tachky',
              levelTime: '2017-12-01T19:57:04+01:00',
              additionsTime: 1101000,
              timeout: false,
              duration: 1101000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 5,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:04:03+01:00',
              additionsTime: null,
              timeout: false,
              duration: 413000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 6,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:07:28+01:00',
              additionsTime: null,
              timeout: false,
              duration: 205000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 7,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:16:13+01:00',
              additionsTime: null,
              timeout: false,
              duration: 525000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 8,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:24:13+01:00',
              additionsTime: null,
              timeout: false,
              duration: 418000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 9,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:24:57+01:00',
              additionsTime: null,
              timeout: false,
              duration: 44000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 10,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:29:06+01:00',
              additionsTime: null,
              timeout: false,
              duration: 249000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 11,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:44:58+01:00',
              additionsTime: null,
              timeout: false,
              duration: 952000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 12,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:53:31+01:00',
              additionsTime: null,
              timeout: false,
              duration: 229000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 13,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:58:28+01:00',
              additionsTime: null,
              timeout: false,
              duration: 297000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 14,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:01:53+01:00',
              additionsTime: null,
              timeout: false,
              duration: 205000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 15,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:03:58+01:00',
              additionsTime: null,
              timeout: false,
              duration: 125000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 16,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:09:15+01:00',
              additionsTime: null,
              timeout: false,
              duration: 205000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 17,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:17:35+01:00',
              additionsTime: null,
              timeout: false,
              duration: 500000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 18,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:21:09+01:00',
              additionsTime: null,
              timeout: false,
              duration: 214000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 19,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:23:09+01:00',
              additionsTime: null,
              timeout: true,
              duration: 120000,
              bestTime: false,
            },
          ],
          [
            {
              id: 154808,
              levelIdx: 0,
              name: 'Dream team best',
              levelTime: '2017-12-01T19:24:37+01:00',
              additionsTime: null,
              timeout: false,
              duration: 277000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 1,
              name: 'Dream team best',
              levelTime: '2017-12-01T19:29:45+01:00',
              additionsTime: null,
              timeout: false,
              duration: 308000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 2,
              name: 'Закон Ома',
              levelTime: '2017-12-01T19:43:13+01:00',
              additionsTime: null,
              timeout: false,
              duration: 778000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 3,
              name: 'Закон Ома',
              levelTime: '2017-12-01T19:45:36+01:00',
              additionsTime: -143000,
              timeout: false,
              duration: 143000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 4,
              name: 'Dream team best',
              levelTime: '2017-12-01T19:57:10+01:00',
              additionsTime: 180000,
              timeout: false,
              duration: 180000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 5,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:12:25+01:00',
              additionsTime: null,
              timeout: false,
              duration: 904000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 6,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:14:40+01:00',
              additionsTime: null,
              timeout: false,
              duration: 135000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 7,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:17:15+01:00',
              additionsTime: null,
              timeout: false,
              duration: 155000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 8,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:31:37+01:00',
              additionsTime: null,
              timeout: false,
              duration: 924000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 9,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:33:01+01:00',
              additionsTime: null,
              timeout: false,
              duration: 84000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 10,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:34:47+01:00',
              additionsTime: null,
              timeout: false,
              duration: 106000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 11,
              name: 'Dream team best',
              levelTime: '2017-12-01T20:49:42+01:00',
              additionsTime: null,
              timeout: false,
              duration: 895000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 12,
              name: 'Закон Ома',
              levelTime: '2017-12-01T20:56:27+01:00',
              additionsTime: null,
              timeout: false,
              duration: 689000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 13,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:00:44+01:00',
              additionsTime: null,
              timeout: false,
              duration: 257000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 14,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:03:08+01:00',
              additionsTime: null,
              timeout: false,
              duration: 144000,
              bestTime: true,
            },
            {
              id: 13977,
              levelIdx: 15,
              name: 'Закон Ома',
              levelTime: '2017-12-01T21:05:50+01:00',
              additionsTime: null,
              timeout: false,
              duration: 162000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 16,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:09:32+01:00',
              additionsTime: null,
              timeout: false,
              duration: 334000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 17,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:19:36+01:00',
              additionsTime: null,
              timeout: false,
              duration: 604000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 18,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:21:58+01:00',
              additionsTime: null,
              timeout: false,
              duration: 142000,
              bestTime: true,
            },
            {
              id: 154808,
              levelIdx: 19,
              name: 'Dream team best',
              levelTime: '2017-12-01T21:23:58+01:00',
              additionsTime: null,
              timeout: true,
              duration: 120000,
              bestTime: false,
            },
          ],
          [
            {
              id: 13977,
              levelIdx: 0,
              name: 'Закон Ома',
              levelTime: '2017-12-01T19:24:56+01:00',
              additionsTime: null,
              timeout: false,
              duration: 296000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 1,
              name: 'Закон Ома',
              levelTime: '2017-12-01T19:30:15+01:00',
              additionsTime: null,
              timeout: false,
              duration: 319000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 2,
              name: 'Dream team best',
              levelTime: '2017-12-01T19:51:45+01:00',
              additionsTime: null,
              timeout: true,
              duration: 1320000,
              bestTime: false,
            },
            {
              id: 154808,
              levelIdx: 3,
              name: 'Dream team best',
              levelTime: '2017-12-01T19:54:10+01:00',
              additionsTime: -145000,
              timeout: false,
              duration: 145000,
              bestTime: false,
            },
            {
              id: 13977,
              levelIdx: 4,
              name: 'Закон Ома',
              levelTime: '2017-12-01T19:57:21+01:00',
              additionsTime: 705000,
              timeout: false,
              duration: 705000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 5,
              name: 'Tachky',
              levelTime: '2017-12-01T20:14:50+01:00',
              additionsTime: null,
              timeout: false,
              duration: 1066000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 6,
              name: 'Tachky',
              levelTime: '2017-12-01T20:17:37+01:00',
              additionsTime: null,
              timeout: false,
              duration: 167000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 7,
              name: 'Tachky',
              levelTime: '2017-12-01T20:30:15+01:00',
              additionsTime: null,
              timeout: false,
              duration: 758000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 8,
              name: 'Tachky',
              levelTime: '2017-12-01T20:39:31+01:00',
              additionsTime: null,
              timeout: false,
              duration: 556000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 9,
              name: 'Tachky',
              levelTime: '2017-12-01T20:41:17+01:00',
              additionsTime: null,
              timeout: false,
              duration: 106000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 10,
              name: 'Tachky',
              levelTime: '2017-12-01T20:44:25+01:00',
              additionsTime: null,
              timeout: false,
              duration: 188000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 11,
              name: 'Tachky',
              levelTime: '2017-12-01T20:57:52+01:00',
              additionsTime: null,
              timeout: false,
              duration: 807000,
              bestTime: true,
            },
            {
              id: 140550,
              levelIdx: 12,
              name: 'Tachky',
              levelTime: '2017-12-01T21:03:42+01:00',
              additionsTime: null,
              timeout: false,
              duration: 350000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 13,
              name: 'Tachky',
              levelTime: '2017-12-01T21:22:16+01:00',
              additionsTime: null,
              timeout: false,
              duration: 1114000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 14,
              name: 'Tachky',
              levelTime: '2017-12-01T21:25:46+01:00',
              additionsTime: null,
              timeout: false,
              duration: 210000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 15,
              name: 'Tachky',
              levelTime: '2017-12-01T21:27:19+01:00',
              additionsTime: null,
              timeout: false,
              duration: 93000,
              bestTime: true,
            },
            {
              id: 140550,
              levelIdx: 16,
              name: 'Tachky',
              levelTime: '2017-12-01T21:33:36+01:00',
              additionsTime: null,
              timeout: false,
              duration: 377000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 17,
              name: 'Tachky',
              levelTime: '2017-12-01T21:46:03+01:00',
              additionsTime: null,
              timeout: false,
              duration: 747000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 18,
              name: 'Tachky',
              levelTime: '2017-12-01T21:52:00+01:00',
              additionsTime: null,
              timeout: false,
              duration: 357000,
              bestTime: false,
            },
            {
              id: 140550,
              levelIdx: 19,
              name: 'Tachky',
              levelTime: '2017-12-01T21:54:00+01:00',
              additionsTime: null,
              timeout: true,
              duration: 120000,
              bestTime: false,
            },
          ],
        ],
        finishResults: [
          {
            id: 13977,
            levelIdx: null,
            name: 'Закон Ома',
            levelTime: '2017-12-01T21:23:09+01:00',
            additionsTime: 562000,
            timeout: false,
            duration: 7389000,
            extraBonus: 0,
            closedLevels: 20,
          },
          {
            id: 154808,
            levelIdx: null,
            name: 'Dream team best',
            levelTime: '2017-12-01T21:23:58+01:00',
            additionsTime: 35000,
            timeout: false,
            duration: 7438000,
            extraBonus: 0,
            closedLevels: 20,
          },
          {
            id: 140550,
            levelIdx: null,
            name: 'Tachky',
            levelTime: '2017-12-01T21:54:00+01:00',
            additionsTime: 743000,
            timeout: false,
            duration: 9240000,
            extraBonus: 0,
            closedLevels: 20,
          },
        ],
      });
      const resultedState = gameDetailsReducer(mutatedState, action);
      expect(expectedState).toEqual(resultedState);
    });
  });
  describe('RequestGameDetails', () => {
    describe('RequestGameDetailsAction', () => {
      it('should set loading flag to true', () => {
        const action = GAME_DETAILS_ACTIONS.requestGameDetails({ id: 60124, domain: 'rivne.en.cx' });
        const expectedState = mutateState({
          isLoading: true,
        });
        const resultedState = gameDetailsReducer(initialState, action);
        expect(expectedState).toEqual(resultedState);
      });
    });
    describe('RequestGameDetailsFailedAction', () => {
      it('should set loading flag to false', () => {
        const action = GAME_DETAILS_ACTIONS.requestGameDetailsFailed({});
        const mutatedState = mutateState({
          isLoading: true,
        });
        const expectedState = mutateState({
          isLoading: false,
        });
        const resultedState = gameDetailsReducer(mutatedState, action);
        expect(expectedState).toEqual(resultedState);
      });
    });
    describe('RequestGameDetailsSuccessAction', () => {
      it('should set loading flag to false and store data to store', () => {
        const action = GAME_DETAILS_ACTIONS.requestGameDetailsSuccess({
          data: mockedGameDetails,
        });
        const mutatedState = mutateState({
          isLoading: true,
        });
        const expectedState = mutateState({
          isLoading: false,
          gameInfo: mockedGameDetails.info,
          levels: mockedGameDetails.stat.Levels,
          dataByTeam: mockedGameDetails.stat.DataByTeam,
          dataByLevels: mockedGameDetails.stat.DataByLevels,
          finishResults: mockedGameDetails.stat.FinishResults,
          selectedTotalTab: 0,
          originalLevels: mockedGameDetails.stat.Levels,
        });
        const resultedState = gameDetailsReducer(mutatedState, action);
        expect(expectedState).toEqual(resultedState);
      });
    });
  });
  describe('SaveLevelsTypes', () => {
    describe('SaveLevelsTypesAction', () => {
      it('should set loading flag to true', () => {
        const action = GAME_DETAILS_ACTIONS.saveLevelsTypes();
        const expectedState = mutateState({
          isLoading: true,
        });
        const resultedState = gameDetailsReducer(initialState, action);
        expect(expectedState).toEqual(resultedState);
      });
    });
    describe('SaveLevelsTypesFailedAction', () => {
      it('should set loading flag to false', () => {
        const action = GAME_DETAILS_ACTIONS.saveLevelsTypesFailed({});
        const mutatedState = mutateState({
          isLoading: true,
        });
        const expectedState = mutateState({
          isLoading: false,
        });
        const resultedState = gameDetailsReducer(mutatedState, action);
        expect(expectedState).toEqual(resultedState);
      });
    });
    describe('SaveLevelsTypesSuccessAction', () => {
      it('should set loading flag to false and store data to store', () => {
        const action = GAME_DETAILS_ACTIONS.saveLevelsTypesSuccess();
        const mutatedState = mutateState({
          isLoading: true,
          levels: mockedGameDetails.stat.Levels,
          originalLevels: undefined,
        });
        const expectedState = mutateState({
          isLoading: false,
          levels: mockedGameDetails.stat.Levels,
          originalLevels: mockedGameDetails.stat.Levels,
        });
        const resultedState = gameDetailsReducer(mutatedState, action);
        expect(expectedState).toEqual(resultedState);
      });
    });
  });
});
